Project 3: Using Bootstrap - Milestone 2
Vagyasri/Project3-newsweek pull request #2
Opened 2021-04-07 10:45 UTC by barackm

In this milestone we have implemented the following features:

- **Column 1** 
           Featured stories
           Sponsored insights / Rankings

- **Column 2**
          Top story
          My turn
          Culture & travel
          More stories
          Latest news

- **Column 3**
         The debate
         Opinion
         Sponsored insights / Rankings
         Free signup

We made the responsive design of all these sections using the bootstrap grid and flex-box.

2021-04-07 12:32 UTC, descholar-ceo requested changes
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @barackm and @Vagyasri  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your almost clone looks like the original page and it is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.

#### The following is the list of what you have implemented successfully
:+1: Usage of semantic HTML tags :heavy_check_mark:
:+1: Almost all sections have been implemented well :heavy_check_mark: 
:+1: Most of CSS best practices are respected :heavy_check_mark: 
:+1: Very good pull request description :heavy_check_mark: 

#### :warning: However we need to make few changes to mark this project approved. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 

- [x] I highly recommend you to not overuse `!important` in your CSS styling, as it a CSS common mistake, the overusage of `!important` makes your life difficult in time of maintaining or debugging your codes, please read more about that with [this article](https://speckyboy.com/good-bad-css-practices/)

- [x] Since this project's main focus is using bootstrap, you should reduce your CSS file by applying bootstrap classes instead of writting your own CSS, for that please read my inline comments in your css file, and fix all issues I pointed out. And please note that the following codes have their bootstrap classes already which implement the same:

```css
    display: flex;
    justify-content: center;
    align-items: center;
    height: auto;
```

=> In the context of this project, choose to use bootstrap instead of writing your own css codes

- [x] In the column 1 and Column 3, I couldn't see the `SPONSORED INSIGHT` from your clone, so I will consider it as a not implemented section

- [ ] Pictures from your clone are being stretched on all screens between 484px to 766px of width, hence that is making your clone to not look like the original website, amongst the requirements of this project is to make sure that you make an exact replicate of the original website, kindly fix this issue,

| Your clone | Original page |
| --- | --- |
| ![Screenshot from 2021-04-07 14-13-27](https://user-images.githubusercontent.com/56886064/113866208-53714280-97ad-11eb-9248-8d21affd63b2.png) | ![Screenshot from 2021-04-07 14-13-54](https://user-images.githubusercontent.com/56886064/113866266-6552e580-97ad-11eb-9764-ccc76e0fc5ad.png) |

:point_right: Could you see the difference :question: :question: :question: 

- [x] For the mobile version there is a small issue that you need to fix, the order of sections should be arranged as it is on the screenshot below:

| Your clone | Original page |
| --- | --- |
| ![Screenshot from 2021-04-07 14-21-47](https://user-images.githubusercontent.com/56886064/113866341-7dc30000-97ad-11eb-9c33-1508474bea73.png) |![Screenshot from 2021-04-07 06-55-56](https://user-images.githubusercontent.com/56886064/113866414-96331a80-97ad-11eb-9936-96b32ede5f64.png)|

:point_right: Could you see the difference :question: :question: :question: 

# [Optional changes] :yellow_circle: 

- [x] Add a descriptive text on all alt attributes of all images
- [x] The issues link is redirecting in a wrong place, currently it's redirecting me on my personal issues page, which is wrong, it should redirect on this project's issues page
___

_:warning: Reminder: As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561#), when you reach to the limit of 3 code reviews and your project was not approved, you will need to repeat the project. => You are now left with 2 chance to get a review on this project. So implement the requested changes very carefully. If you think that the code review was not fair, you can request a second-opinion using [this form](https://airtable.com/shrmBIv6cXYrq4Fgv)._

_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

2021-04-07 12:32 UTC, descholar-ceo commented on style.css
> +  margin-bottom: 1px !important;
[required] You can achieve this margin-bottom by using a bootstrap class, please do remove this css codes and use bootstrap class

2021-04-07 12:32 UTC, descholar-ceo commented on style.css
> +  width: 100%;
[required] You can achieve this `width: 100%` by using a bootstrap class, please focus on bootstrap instead of writing your own css

2021-04-07 12:32 UTC, descholar-ceo commented on style.css
> +}
[required] You can achieve this `width: 100%` and `height 100%` by using a bootstrap class, please focus on bootstrap instead of writing your own css

2021-04-07 12:32 UTC, descholar-ceo commented on style.css
> +  width: 100%;
[required] You can achieve this `width: 100%` by using a bootstrap class, please focus on bootstrap instead of writing your own css

2021-04-07 12:32 UTC, descholar-ceo commented on style.css
> +}
[required] You can achieve this `width: 100%` and `height 100%` by using a bootstrap class, please focus on bootstrap instead of writing your own css

2021-04-07 12:32 UTC, descholar-ceo commented on style.css
> +  left: 0;
[required] This css code has been repeated, more than one time, this violates the DRY rule of css codes, so to respect that rule you can just create a class and make it hold all of those repeating properties and then apply that class to all of elements which need those properties

2021-04-07 12:32 UTC, descholar-ceo commented on style.css
> +  margin-bottom: 1px !important;
[required] You can achieve this ` margin-bottom: 1px` by using bootstrap class, please focus on using bootstrap whenever it's possible

2021-04-07 12:32 UTC, descholar-ceo commented on style.css
> +  color: white;
[required] You can achieve this `color: white` with using bootstrap class, please focus on using bootstrap classes

2021-04-07 12:32 UTC, descholar-ceo commented on style.css
> +}
[required] You can achieve all of the margin you are writing here, by applying bootstrap classes, please do focus on using bootstrap classes

2021-04-07 12:32 UTC, descholar-ceo commented on style.css
> +  }
[required] The margin and width you are styling with raw css codes, you can achieve the same result by applying bootstrap classes

2021-04-07 12:32 UTC, descholar-ceo commented on style.css
> +    margin: 0 auto;
[required] You can bootstrap classes, here as well

2021-04-07 12:32 UTC, descholar-ceo commented on style.css
> +  }
[required] Use bootstrap classes here as well

2021-04-07 12:32 UTC, descholar-ceo commented on style.css
> +  }
[required] Use bootstrap classes here as well

2021-04-07 14:01 UTC, Vagyasri commented on style.css
> +  margin-bottom: 1px !important;
Edited.

2021-04-07 14:01 UTC, Vagyasri commented on style.css
> +}
Edited.

2021-04-07 14:02 UTC, Vagyasri commented on style.css
> +  width: 100%;
Done.

2021-04-07 14:04 UTC, Vagyasri commented on style.css
> +}
Edited.

2021-04-07 14:06 UTC, Vagyasri commented on style.css
> +  margin-bottom: 1px !important;
Edited.

2021-04-07 14:10 UTC, Vagyasri commented on style.css
> +}
Edited.

2021-04-07 14:16 UTC, Vagyasri commented on style.css
> +  }
Applying "margin: 0 auto;" using bootstrap is not possible as per our understanding. Kindly, help if you know a solution to this.

2021-04-07 14:16 UTC, Vagyasri commented on style.css
> +    margin: 0 auto;
Applying "margin: 0 auto;" using bootstrap is not possible as per our understanding. Kindly, help if you know a solution to this.

2021-04-07 14:22 UTC, Vagyasri commented on style.css
> +  }
.image-round {
    width: 40px;
    height: 40px;
  }

In bootstrap, we don't get the exact same pixels as those are in percentage.

2021-04-07 14:22 UTC, Vagyasri commented on style.css
> +  }
Any suggestion?

2021-04-07 14:24 UTC, Vagyasri commented on style.css
> +  }
Edited.

2021-04-07 16:38 UTC, Vagyasri commented on style.css
> +  color: white;
Edited

2021-04-07 16:41 UTC, Vagyasri commented on style.css
> +  left: 0;
Edited, feel free to comment if you get any similar result.

2021-04-08 10:47 UTC, Vagyasri requested changes, later dismissed
Trying to solve reviewer issue.

2021-04-08 21:00 UTC, Dipeshtwis requested changes
# Status:  ♻️ Changes Required ♻️
 Hi @Vagyasri and @barackm

**You've fixed almost all the requirements from the previous review. Well done.** Here're the major highlights of this PR:
- Your PR title and description are really descriptive.
- Good use of Semantic HTML.

**However, in order to approve, we have to work a little bit more. Please check my comments below and fix them as appropriate.**

## For Approval

- [x] Still, there is an issue with `featured stories` images. I have used the above comment to show this.

![Screenshot (1313)](https://user-images.githubusercontent.com/22434660/114095075-a3015c80-98da-11eb-83b1-bf6a3af3678a.png)

- [x] Use the DRY (Do not repeat yourself) principle wherever possible. I have mentioned some of them in the comments.

## Please make the required changes and submit another review request when you are done.


## Optional

- [x] For now, I can see you have used many similar comments in CSS.
` /* couldn't find any bootstrap class for this */`. Remove all so that it will not ruin your clean code.
## Reminder

**"As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) now, you have only 1 code review left for this project. If you think that the code review was not fair, you can [request a second opinion using this form](https://airtable.com/shrQAqnBwek5a0O0s). "**


(Feel free to contact me on slack by the handle of  **deep** if you have any additional questions).
Happy Coding
[Dipesh Kumar](https://deeptwist.tk) | [Twitter](https://twitter.com/97deepeshkumar)

2021-04-08 21:00 UTC, Dipeshtwis commented on style.css
> +    margin: 0 auto;
You have used `@media screen and (max-width: 768px)` so many times for different classes. See line no. 586 and 334.

2021-04-08 21:00 UTC, Dipeshtwis commented on style.css
> +    height: 246px;
Same with 480px . Already used in line no. 394. Use only one media query for one screen.

2021-04-08 22:37 UTC, Dipeshtwis approved these changes
# Status: Approved ✔️

## Hi @barackm  &  @Vagyasri 

Good job on implementing the suggested changes. Well done. **You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**


Cheers and Happy coding!👏👏👏

Code review by **Dipesh Kumar**
(Feel free to contact me on slack by the handle of  **deep** if you have any additional questions).
[Dipesh Kumar](https://deeptwist.tk) | [Twitter](https://twitter.com/97deepeshkumar)

2021-04-09 10:38 UTC, merged